sudo: required
language: go
services:
  - docker
go:
  - 1.9
  - tip
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - DOCKER_USER=stratumndocker
install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/golang/lint/golint
  - dep ensure
  - curl -sSL https://goo.gl/Q3YRTi | bash
script:
  - make coverage && make lint
after_success:
  - bash <(curl -s https://codecov.io/bash)