[[constraint]]
  name = "github.com/stratumn/sdk"
  revision = "e9fcf645dac81efb3130c9ca88eaa2d897c41b71"

[[constraint]]
  name = "github.com/hyperledger/fabric"
  version = "1.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/hyperledger/fabric-sdk-go"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[override]]
  name = "github.com/op/go-logging"
  revision = "970db520ece77730c7e4724c61121037378659d9"

[[constraint]]
  branch = "master"
  name = "github.com/docker/libcompose"

[[override]]
  branch = "master"
  name = "github.com/docker/distribution"

[[override]]
  branch = "master"
  name = "github.com/opencontainers/runc"

[[override]]
  name = "github.com/xeipuuv/gojsonschema"
  revision = "93e72a773fade158921402d6a24c819b48aba29d"
