FROM hyperledger/fabric-tools:x86_64-1.1.0

COPY vendor/github.com $GOPATH/src/github.com
COPY . $GOPATH/src/github.com/stratumn/fabricstore
COPY chaincode/pop $GOPATH/src/github.com/stratumn/chaincode/pop